--- packaging/Dockerfile.mockbuild
+++ packaging/Dockerfile.mockbuild
@@ -5,7 +5,7 @@
 #
 
 # Pull base image
-FROM fedora:latest
+FROM fedora:35
 LABEL maintainer="daos@daos.groups.io"
 
 # use same UID as host and default value of 1000 if not specified
